name: pygbag_build
on: [workflow_dispatch]

jobs:
  build-pygbag:
    name: Build and deploy pygbag app to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - name: Debug build output
      run: |
        find build -maxdepth 4 -type d
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pygbag and build project
      run: |
        python -m pip install --upgrade pip
        python -m pip install pygbag
        python -m pygbag --build --app-name index main.py

    - name: Deploy to GitHub Pages (gh-pages branch)
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/web/index
        clean: true
